name: Build Daily arXiv pages

on:
  workflow_dispatch: {}
  schedule:
    # Weekdays at 05:10 UTC (07:10 Prague in summer / 06:10 in winter)
    - cron: "10 5 * * 1-5"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run generator
        run: |
          python DailyArXiV.py
          echo "== Workspace after generator =="
          ls -al

      - name: Collect outputs into docs/ (dated + stable) and disable Jekyll
        shell: bash
        run: |
          set -euo pipefail

          # Find the most recent *_Priority.html the script created
          mapfile -t STAMPS < <(ls -1 *_Priority.html 2>/dev/null | sed 's/_Priority\.html$//' | sort -r)
          if [ ${#STAMPS[@]} -eq 0 ]; then
            echo "::error title=No generated files found::Expected *_Priority.html after running DailyArXiV.py"
            exit 1
          fi
          STAMP="${STAMPS[0]}"
          echo "Detected STAMP=$STAMP"
          echo "STAMP=$STAMP" >> "$GITHUB_ENV"

          mkdir -p docs

          # Copy dated files
          cp "${STAMP}_Priority.html"  "docs/${STAMP}_Priority.html"
          cp "${STAMP}_Main.html"      "docs/${STAMP}_Main.html"
          cp "${STAMP}_Interest.html"  "docs/${STAMP}_Interest.html"

          # Stable (today) URLs
          cp "${STAMP}_Priority.html"  "docs/Priority.html"
          cp "${STAMP}_Main.html"      "docs/Main.html"
          cp "${STAMP}_Interest.html"  "docs/Interest.html"

          # Ensure Pages treats this as static (no Jekyll build)
          touch docs/.nojekyll

          echo "== docs/ contents =="
          ls -al docs

      - name: Commit and push changes (if any)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet -- docs; then
            git add -A docs
            git commit -m "Daily arXiv pages: update docs/ and add ${STAMP}_*.html"
            git push
            echo "Committed and pushed updated docs/"
          else
            echo "No changes to commit."
          fi
