name: Build Daily arXiv pages

on:
  workflow_dispatch: {}
  schedule:
    # Weekdays at 05:10 UTC (07:10 Prague summer / 06:10 winter)
    - cron: "10 5 * * 1-5"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run generator
        run: |
          python DailyArXiV.py

      - name: Collect outputs into docs/ (dated + stable) and disable Jekyll
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p docs

          # Detect date stamp from produced files (e.g. 20250915_Priority.html)
          STAMP=$(ls -1 *_Priority.html | head -n1 | cut -d'_' -f1)
          echo "Detected STAMP=$STAMP"

          # Copy dated files
          cp "${STAMP}_Priority.html"  "docs/${STAMP}_Priority.html"
          cp "${STAMP}_Main.html"      "docs/${STAMP}_Main.html"
          cp "${STAMP}_Interest.html"  "docs/${STAMP}_Interest.html"

          # Stable URLs (today)
          cp "${STAMP}_Priority.html"  "docs/Priority.html"
          cp "${STAMP}_Main.html"      "docs/Main.html"
          cp "${STAMP}_Interest.html"  "docs/Interest.html"

          # Disable Jekyll so Pages serves plain HTML (no SCSS/theme processing)
          touch docs/.nojekyll

      - name: Commit and push changes (if any)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet -- docs; then
            git add docs
            git commit -m "Daily arXiv pages: update docs/ and add ${STAMP}_*.html"
            git push
          else
            echo "No changes to commit."
          fi
