name: Sanity: Run DailyArXiV.py
on: { workflow_dispatch: {} }

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show first lines & raw bytes of DailyArXiV.py
        run: |
          echo "== FIRST 10 LINES =="
          nl -ba DailyArXiV.py | sed -n '1,10p'
          echo
          echo "== FIRST 64 BYTES (hex) =="
          xxd -l 64 -g 1 DailyArXiV.py || true
          echo
          if head -n1 DailyArXiV.py | grep -q '```'; then
            echo "::error ::Your file starts with Markdown code fences (```...). Remove those lines."
            exit 1
          fi

      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Compile first (catch syntax with filename/line)
        run: python -m py_compile DailyArXiV.py

      - name: Run script & list outputs
        run: |
          python DailyArXiV.py
          echo "== TOP-LEVEL HTML FILES =="
          ls -1 *.html || true

      - name: Upload generated HTML (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: arxiv-html
          path: |
            *_Priority.html
            *_Main.html
            *_Interest.html
          if-no-files-found: error
